resource_group_name_apim = "zgebs-workbench-dev-api-rg"
location = "north europe"
apim_name = "workbenchAPI-ManagerDEV"
company_name = "zgebs"
publisher_email = "example@example.com"
sku_name_apim = "Developer_1"
